import type { IconName } from '@/components/Icons'

export type SportProfile = {
  id: string
  label: string
  icon: IconName
  lastReviewed: string
  keyDemands: string[]
  mobilityRisks: string[]
  targetAreas: string[]
  routineBias: string
}

export const SPORT_PROFILES: SportProfile[] = [
  {
    id: 'golf',
    label: 'Golf',
    icon: 'golf',
    lastReviewed: '2026-04-16',
    keyDemands: ['hip rotation', 'thoracic rotation', 'shoulder turn', 'lateral flexion'],
    mobilityRisks: ['limited hip turn can increase lumbar loading', 'restricted thoracic rotation can reduce swing separation'],
    targetAreas: ['spine', 'hips', 'shoulders'],
    routineBias: 'Open up rotation first, then build controlled trunk and shoulder range for cleaner swing mechanics.',
  },
  {
    id: 'afl',
    label: 'AFL',
    icon: 'afl',
    lastReviewed: '2026-04-16',
    keyDemands: ['hip mobility', 'ankle dorsiflexion', 'shoulder overhead range', 'thoracic rotation'],
    mobilityRisks: ['stiff hips and ankles can affect change of direction and kicking mechanics', 'restricted thoracic or shoulder range can reduce overhead freedom'],
    targetAreas: ['hips', 'shoulders', 'spine'],
    routineBias: 'Bias the session toward hips and trunk first, then support overhead and running mechanics.',
  },
  {
    id: 'rugby',
    label: 'Rugby',
    icon: 'rugby',
    lastReviewed: '2026-04-16',
    keyDemands: ['neck mobility', 'thoracic extension and rotation', 'hip extension', 'shoulder internal rotation'],
    mobilityRisks: ['limited trunk and hip extension can affect sprinting and contact positions', 'stiff shoulders can reduce comfort in grappling and ball carry positions'],
    targetAreas: ['spine', 'hips', 'shoulders'],
    routineBias: 'Prioritize trunk and hip positions that support contact, sprinting, and repeated collision demands.',
  },
  {
    id: 'soccer',
    label: 'Soccer',
    icon: 'soccer',
    lastReviewed: '2026-04-16',
    keyDemands: ['hip adductor length', 'ankle dorsiflexion', 'thoracic rotation', 'hip flexor freedom'],
    mobilityRisks: ['restricted hips and ankles can increase groin and overload patterns', 'reduced rotation can limit striking and directional change mechanics'],
    targetAreas: ['hips', 'spine', 'shoulders'],
    routineBias: 'Give most of the session to hips and trunk so cutting, striking, and sprinting positions feel cleaner.',
  },
  {
    id: 'wrestling',
    label: 'Wrestling',
    icon: 'wrestling',
    lastReviewed: '2026-04-16',
    keyDemands: ['shoulder internal rotation', 'thoracic mobility', 'hip mobility', 'neck control'],
    mobilityRisks: ['stiff shoulders and thoracic spine can reduce mat control positions', 'restricted hips can limit stance depth and scramble positions'],
    targetAreas: ['shoulders', 'spine', 'hips'],
    routineBias: 'Build shoulder and trunk freedom first, then support loaded hip positions and mat control.',
  },
  {
    id: 'weightlifting',
    label: 'Weightlifting',
    icon: 'weightlifting',
    lastReviewed: '2026-04-16',
    keyDemands: ['thoracic extension', 'ankle dorsiflexion', 'shoulder overhead range', 'hip flexion'],
    mobilityRisks: ['restricted ankles and trunk can disrupt receiving positions', 'stiff shoulders can limit overhead lockout quality'],
    targetAreas: ['shoulders', 'spine', 'hips'],
    routineBias: 'Bias the routine toward overhead and receiving-position mobility with strong trunk control.',
  },
  {
    id: 'cricket',
    label: 'Cricket',
    icon: 'cricket',
    lastReviewed: '2026-04-16',
    keyDemands: ['hip rotation', 'thoracic rotation', 'shoulder external rotation', 'wrist freedom'],
    mobilityRisks: ['limited rotation can overload the lumbar spine', 'stiff shoulders can affect throwing and bowling positions'],
    targetAreas: ['shoulders', 'spine', 'hips'],
    routineBias: 'Emphasize rotational mechanics and shoulder freedom for throwing, bowling, and batting demands.',
  },
  {
    id: 'tennis',
    label: 'Tennis',
    icon: 'tennis',
    lastReviewed: '2026-04-16',
    keyDemands: ['hip mobility', 'shoulder external rotation', 'thoracic rotation', 'ankle reactivity'],
    mobilityRisks: ['restricted trunk and shoulder range can affect serve and forehand positions', 'stiff hips can reduce movement quality into open stances'],
    targetAreas: ['shoulders', 'spine', 'hips'],
    routineBias: 'Keep the session rotation-heavy with shoulder support for serve and repeated stroke mechanics.',
  },
  {
    id: 'basketball',
    label: 'Basketball',
    icon: 'basketball',
    lastReviewed: '2026-04-16',
    keyDemands: ['hip flexor freedom', 'ankle dorsiflexion', 'thoracic extension', 'shoulder mobility'],
    mobilityRisks: ['restricted ankles and hips can affect landing and cutting positions', 'stiff trunk can reduce overhead and shooting mechanics'],
    targetAreas: ['hips', 'spine', 'shoulders'],
    routineBias: 'Support jumping and change-of-direction positions by opening ankles, hips, and trunk first.',
  },
  {
    id: 'volleyball',
    label: 'Volleyball',
    icon: 'volleyball',
    lastReviewed: '2026-04-16',
    keyDemands: ['shoulder overhead range', 'thoracic extension', 'hip mobility', 'ankle freedom'],
    mobilityRisks: ['restricted shoulders and thoracic spine can reduce overhead efficiency', 'stiff hips and ankles can affect landing positions'],
    targetAreas: ['shoulders', 'spine', 'hips'],
    routineBias: 'Give priority to overhead mechanics, then support jump and landing positions through hips and ankles.',
  },
  {
    id: 'netball',
    label: 'Netball',
    icon: 'netball',
    lastReviewed: '2026-04-16',
    keyDemands: ['hip mobility', 'ankle dorsiflexion', 'shoulder freedom', 'deceleration positions'],
    mobilityRisks: ['restricted hips and ankles can affect braking and landing positions', 'stiff shoulders can limit overhead catch and pass positions'],
    targetAreas: ['hips', 'shoulders', 'spine'],
    routineBias: 'Bias toward hips and ankles first, then support overhead freedom and torso control.',
  },
  {
    id: 'bjj',
    label: 'BJJ',
    icon: 'bjj',
    lastReviewed: '2026-04-16',
    keyDemands: ['hip mobility', 'spinal rotation', 'shoulder internal rotation', 'neck and wrist comfort'],
    mobilityRisks: ['restricted hips and trunk can reduce guard and scramble positions', 'stiff shoulders can affect framing and posting positions'],
    targetAreas: ['hips', 'spine', 'shoulders'],
    routineBias: 'Support ground positions with hip and trunk range first, then add shoulder control.',
  },
  {
    id: 'kickboxing',
    label: 'Kickboxing',
    icon: 'kickboxing',
    lastReviewed: '2026-04-16',
    keyDemands: ['hip flexor freedom', 'hip rotation', 'thoracic rotation', 'shoulder mobility'],
    mobilityRisks: ['limited hips can affect kicking height and comfort', 'restricted trunk rotation can reduce striking fluidity'],
    targetAreas: ['hips', 'spine', 'shoulders'],
    routineBias: 'Keep the routine hip- and trunk-led so kicking and striking mechanics feel less restricted.',
  },
  {
    id: 'muaythai',
    label: 'Muay Thai',
    icon: 'muaythai',
    lastReviewed: '2026-04-16',
    keyDemands: ['hip flexor freedom', 'hip rotation', 'thoracic rotation', 'shoulder and knee freedom'],
    mobilityRisks: ['restricted hips can reduce kicking and knee comfort', 'stiff trunk can limit rotational striking quality'],
    targetAreas: ['hips', 'spine', 'shoulders'],
    routineBias: 'Bias the session toward hips and rotation, then support upper-body striking positions.',
  },
  {
    id: 'waterpolo',
    label: 'Water Polo',
    icon: 'waterpolo',
    lastReviewed: '2026-04-16',
    keyDemands: ['shoulder overhead range', 'thoracic rotation', 'hip flexor freedom', 'trunk extension'],
    mobilityRisks: ['restricted shoulders and thoracic spine can affect throwing volume', 'stiff hips can reduce eggbeater comfort and stability'],
    targetAreas: ['shoulders', 'spine', 'hips'],
    routineBias: 'Prioritize overhead shoulder and trunk rotation work, then support hip positions needed for stability in the water.',
  },
  {
    id: 'highjump',
    label: 'High Jump',
    icon: 'highjump',
    lastReviewed: '2026-04-16',
    keyDemands: ['hip extension', 'ankle stiffness and range', 'thoracic extension', 'front-side mechanics'],
    mobilityRisks: ['restricted hips and trunk can reduce take-off positions', 'limited ankle freedom can affect approach and penultimate mechanics'],
    targetAreas: ['hips', 'spine', 'shoulders'],
    routineBias: 'Bias the routine toward hip extension and trunk extension, then support elastic approach mechanics.',
  },
  {
    id: 'hurdles',
    label: 'Hurdles',
    icon: 'hurdles',
    lastReviewed: '2026-04-16',
    keyDemands: ['hip flexion', 'hip rotation', 'hamstring length', 'thoracic posture'],
    mobilityRisks: ['restricted hips can reduce trail-leg and lead-leg positions', 'stiff trunk posture can affect sprint rhythm between hurdles'],
    targetAreas: ['hips', 'spine', 'shoulders'],
    routineBias: 'Spend most of the session on hips and trunk so lead-leg and trail-leg positions feel cleaner and faster.',
  },
  {
    id: 'handball',
    label: 'Handball',
    icon: 'handball',
    lastReviewed: '2026-04-16',
    keyDemands: ['shoulder overhead range', 'thoracic rotation', 'hip mobility', 'ankle freedom'],
    mobilityRisks: ['stiff shoulders and thoracic spine can affect overhead throwing volume', 'restricted hips and ankles can affect cutting and landing positions'],
    targetAreas: ['shoulders', 'spine', 'hips'],
    routineBias: 'Open up overhead throwing positions first, then support cutting and landing mechanics through the lower body.',
  },
  {
    id: 'padel',
    label: 'Padel',
    icon: 'padel',
    lastReviewed: '2026-04-16',
    keyDemands: ['thoracic rotation', 'hip mobility', 'shoulder rotation', 'ankle reactivity'],
    mobilityRisks: ['restricted trunk and shoulders can affect racket positions', 'stiff hips and ankles can limit fast directional changes in a small court'],
    targetAreas: ['shoulders', 'spine', 'hips'],
    routineBias: 'Keep the routine rotation-led with enough hip support for repeated short-change movements and racket positions.',
  },
]

export const SPORT_PROFILE_MAP = Object.fromEntries(
  SPORT_PROFILES.map((profile) => [profile.id, profile]),
) as Record<string, SportProfile>
