-- ============================================================================
-- Move & Groove - run this in Supabase Dashboard -> SQL Editor
-- ============================================================================
--
-- Run BLOCK 1 through BLOCK 4 one at a time, in order, and check each result
-- before moving on. Running them separately means a failure names the block it
-- came from instead of aborting the whole script.
--
-- Every block is idempotent and self-contained: it creates what is missing and
-- repairs what is already there, so re-running a block is safe and values an
-- admin has already set are preserved.
--
-- BLOCK 1 and BLOCK 2 both repair tables rather than just creating them,
-- because the original schema files use `create table if not exists`. On a
-- project where the table already exists those scripts do nothing, so columns
-- and constraints changed after the table was first created never reached the
-- live database. Two symptoms traced back to exactly that:
--
--   * "column routines.saved_at does not exist" when starring a workout
--   * completed workouts never reaching the dashboard, because the live
--     progress table still carries check (duration_minutes in (20, 30, 45))
--     while the quiz slider offers 15/20/25/30/35/40/45
--
-- After running these, redeploy the site from main. The database change alone
-- is not enough: the code that reads these values ships in the deploy.
-- ============================================================================


-- ============================================================================
-- BLOCK 1 - public.routines
-- ============================================================================

create table if not exists public.routines (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  title text not null,
  created_at timestamptz not null default now()
);

alter table public.routines add column if not exists sport text;
alter table public.routines add column if not exists areas text[] not null default '{}';
alter table public.routines add column if not exists goal text;
alter table public.routines add column if not exists duration_minutes integer;
alter table public.routines add column if not exists difficulty text;
alter table public.routines add column if not exists summary text;
alter table public.routines add column if not exists evidence_summary text;
alter table public.routines add column if not exists is_saved boolean not null default false;
alter table public.routines add column if not exists saved_at timestamptz;

create index if not exists routines_user_created_at_idx
  on public.routines (user_id, created_at desc);

create index if not exists routines_user_saved_at_idx
  on public.routines (user_id, saved_at desc)
  where is_saved = true;

alter table public.routines enable row level security;

drop policy if exists "Users can read their own routines" on public.routines;
create policy "Users can read their own routines"
  on public.routines for select
  using (auth.uid() = user_id);

drop policy if exists "Users can create their own routines" on public.routines;
create policy "Users can create their own routines"
  on public.routines for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their own routines" on public.routines;
create policy "Users can update their own routines"
  on public.routines for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own routines" on public.routines;
create policy "Users can delete their own routines"
  on public.routines for delete
  using (auth.uid() = user_id);


-- ============================================================================
-- BLOCK 2 - public.progress
-- ============================================================================

create table if not exists public.progress (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  duration_minutes integer not null,
  created_at timestamptz not null default now()
);

alter table public.progress add column if not exists created_at timestamptz not null default now();
alter table public.progress add column if not exists routine_id bigint references public.routines (id) on delete set null;
alter table public.progress add column if not exists completed_at timestamptz not null default now();
alter table public.progress add column if not exists sport text;
alter table public.progress add column if not exists areas text[];
alter table public.progress add column if not exists goal text;

-- Drop whatever check constraint the live table has on duration_minutes and
-- reapply the current one. The loop looks the name up rather than guessing it.
do $$
declare
  existing_constraint text;
begin
  for existing_constraint in
    select con.conname
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace nsp on nsp.oid = rel.relnamespace
    where nsp.nspname = 'public'
      and rel.relname = 'progress'
      and con.contype = 'c'
      and pg_get_constraintdef(con.oid) like '%duration_minutes%'
  loop
    execute format('alter table public.progress drop constraint %I', existing_constraint);
  end loop;
end $$;

alter table public.progress
  add constraint progress_duration_minutes_check
  check (duration_minutes > 0 and duration_minutes <= 45);

create index if not exists progress_user_completed_at_idx
  on public.progress (user_id, completed_at desc);

alter table public.progress enable row level security;

drop policy if exists "Users can read their own progress" on public.progress;
create policy "Users can read their own progress"
  on public.progress for select to authenticated
  using (user_id = auth.uid());

drop policy if exists "Users can create their own progress" on public.progress;
create policy "Users can create their own progress"
  on public.progress for insert to authenticated
  with check (user_id = auth.uid());


-- ============================================================================
-- BLOCK 3 - public.app_config, the admin-editable limits
-- ============================================================================

create table if not exists public.app_config (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

alter table public.app_config add column if not exists updated_at timestamptz not null default now();

alter table public.app_config enable row level security;

-- Signed-in users read the limits so the dashboard shows the same numbers the
-- API enforces.
drop policy if exists "Authenticated users can read app config" on public.app_config;
create policy "Authenticated users can read app config"
  on public.app_config for select to authenticated
  using (true);

-- Deliberately NO insert/update/delete policy. Writes go through the service
-- role key in /api/admin/config, behind requireAdminAccess, so a signed-in user
-- cannot raise their own limits from the browser.

insert into public.app_config (key, value)
values
  ('basic_daily_routine_limit', '2'),
  ('daily_workout_limit', '2')
on conflict (key) do nothing;

-- Raise the daily workout cap. Change '20' to whatever you want; after the
-- deploy this is editable from the admin panel instead of here.
update public.app_config
set value = '20', updated_at = now()
where key = 'daily_workout_limit';

-- PostgREST caches the schema. Without this the API keeps reporting the old
-- shape even though the columns now exist.
notify pgrst, 'reload schema';


-- ============================================================================
-- BLOCK 4 - verification
-- ============================================================================

-- Expect is_saved and saved_at.
select column_name, data_type
from information_schema.columns
where table_schema = 'public' and table_name = 'routines'
  and column_name in ('is_saved', 'saved_at');

-- Expect: duration_minutes > 0 AND duration_minutes <= 45
-- If it still shows in (20, 30, 45), BLOCK 2 did not apply.
select con.conname, pg_get_constraintdef(con.oid) as definition
from pg_constraint con
join pg_class rel on rel.oid = con.conrelid
join pg_namespace nsp on nsp.oid = rel.relnamespace
where nsp.nspname = 'public' and rel.relname = 'progress' and con.contype = 'c';

-- Expect both keys, with daily_workout_limit at the value set in BLOCK 3.
select key, value, updated_at
from public.app_config
order by key;


-- ============================================================================
-- OPTIONAL - what has been logged today
-- ============================================================================
-- Replace the email. Run this if the dashboard still shows no time: it tells
-- you whether rows exist at all.
--
-- select p.completed_at, p.duration_minutes, p.routine_id
-- from public.progress p
-- join auth.users u on u.id = p.user_id
-- where u.email = 'REPLACE_WITH_YOUR_EMAIL'
--   and p.completed_at >= date_trunc('day', now() at time zone 'utc')
-- order by p.completed_at desc;


-- ============================================================================
-- OPTIONAL, DESTRUCTIVE - clear one account's rows for today
-- ============================================================================
-- Only needed to reset a day's count instead of raising the cap. This DELETES
-- rows permanently and cannot be undone. Run the query above first and read the
-- output, so you know exactly what this will remove.
--
-- delete from public.progress p
-- using auth.users u
-- where u.id = p.user_id
--   and u.email = 'REPLACE_WITH_YOUR_EMAIL'
--   and p.completed_at >= date_trunc('day', now() at time zone 'utc');
