-- Move & Groove: persistent generated routines and saved-workout library.
-- Run this once in Supabase Dashboard -> SQL Editor for the production project.

create table if not exists public.routines (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  title text not null,
  sport text,
  areas text[] not null default '{}',
  goal text,
  duration_minutes integer,
  difficulty text,
  summary text,
  evidence_summary text,
  is_saved boolean not null default false,
  saved_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.routine_items (
  id bigint generated by default as identity primary key,
  routine_id bigint not null references public.routines (id) on delete cascade,
  video_id uuid,
  pillar text not null check (pillar in ('prep', 'release', 'activation', 'range')),
  exercise_name text not null,
  target_area text not null,
  sets integer not null default 1,
  reps integer,
  hold_seconds integer,
  rationale text,
  study_citation text,
  order_index integer not null,
  created_at timestamptz not null default now()
);

-- The create-table statements above are no-ops on a project where these tables
-- already exist, so columns added after the first release must be backfilled
-- explicitly. See database/supabase-routines-saved-columns.sql for the incident
-- this guards against ('column routines.saved_at does not exist' in production).
alter table public.routines add column if not exists sport text;
alter table public.routines add column if not exists areas text[] not null default '{}';
alter table public.routines add column if not exists goal text;
alter table public.routines add column if not exists duration_minutes integer;
alter table public.routines add column if not exists difficulty text;
alter table public.routines add column if not exists summary text;
alter table public.routines add column if not exists evidence_summary text;
alter table public.routines add column if not exists is_saved boolean not null default false;
alter table public.routines add column if not exists saved_at timestamptz;

create index if not exists routines_user_created_at_idx
  on public.routines (user_id, created_at desc);

create index if not exists routines_user_saved_at_idx
  on public.routines (user_id, saved_at desc)
  where is_saved = true;

create index if not exists routine_items_routine_order_idx
  on public.routine_items (routine_id, order_index);

alter table public.routines enable row level security;
alter table public.routine_items enable row level security;

drop policy if exists "Users can read their own routines" on public.routines;
create policy "Users can read their own routines"
  on public.routines for select
  using (auth.uid() = user_id);

drop policy if exists "Users can create their own routines" on public.routines;
create policy "Users can create their own routines"
  on public.routines for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their own routines" on public.routines;
create policy "Users can update their own routines"
  on public.routines for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own routines" on public.routines;
create policy "Users can delete their own routines"
  on public.routines for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can read items from their own routines" on public.routine_items;
create policy "Users can read items from their own routines"
  on public.routine_items for select
  using (
    exists (
      select 1 from public.routines
      where routines.id = routine_items.routine_id
        and routines.user_id = auth.uid()
    )
  );

drop policy if exists "Users can create items for their own routines" on public.routine_items;
create policy "Users can create items for their own routines"
  on public.routine_items for insert
  with check (
    exists (
      select 1 from public.routines
      where routines.id = routine_items.routine_id
        and routines.user_id = auth.uid()
    )
  );

drop policy if exists "Users can update items from their own routines" on public.routine_items;
create policy "Users can update items from their own routines"
  on public.routine_items for update
  using (
    exists (
      select 1 from public.routines
      where routines.id = routine_items.routine_id
        and routines.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.routines
      where routines.id = routine_items.routine_id
        and routines.user_id = auth.uid()
    )
  );

drop policy if exists "Users can delete items from their own routines" on public.routine_items;
create policy "Users can delete items from their own routines"
  on public.routine_items for delete
  using (
    exists (
      select 1 from public.routines
      where routines.id = routine_items.routine_id
        and routines.user_id = auth.uid()
    )
  );

-- Ask PostgREST to refresh its schema cache immediately after this migration.
notify pgrst, 'reload schema';
